on: push
jobs:
  conda:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
      - name: Install dependencies
        run: |
          $CONDA/bin/conda env update --file environment.yml --name base
          conda install pytest
      - name: Convert Jupyter notebook
        run: python ./tests/convert_nb.py
      - name: Test problem 1
        run: |
          $CONDA/bin/pytest /tests/p1_test.py
      - name: Test problem 2
        run: |
          $CONDA/bin/pytest /tests/p2_test.py
      - name: Test problem 3
        run: |
          $CONDA/bin/pytest /tests/p3_test.py
